### ISSUE TITLE
Review installation docs

### ISSUE THREAD

**Issue by ottok** [Seravo/openssh-sftp-logging#1]
Tried to build, ran into:
```
cc -W -Wall -O2 -o sftpwrapper sftpwrapper.c config.c proc_pid_util.c 
sftpwrapper.c:9:10: fatal error: errno.h: No such file or directory
 #include <errno.h>
          ^~~~~~~~~
compilation terminated.
In file included from config.c:3:0:
config.h:4:10: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
          ^~~~~~~~~~~~~
compilation terminated.
proc_pid_util.c:8:10: fatal error: errno.h: No such file or directory
 #include <errno.h>
          ^~~~~~~~~
```

Please document build dependencies.

**Comment by ottok** [comment]
OK, this was just `apt install libc-dev`.

**Comment by ottok** [comment]
Next issue is the group name. Should the group be one that includes the sshd process user or every user that could log in?

**Comment by ottok** [comment]
There could be some kind of "screenshot" and examples of `last -RFwx` use so people finding out about this repository immediately get a sense of what it would provide if used.

**Comment by heikkiorsila** [comment]
Please review the documentation changes.
